CKEDITOR.dialog.add("scaytDialog",function(d){var f=d.scayt,k='<p><img src="'+f.getLogo()+'" /></p><p>'+f.getLocal("version")+f.getVersion()+"</p><p>"+f.getLocal("about_throw_copy")+"</p>",l=CKEDITOR.document,i={isChanged:function(){return null===this.newLang||this.currentLang===this.newLang?!1:!0},currentLang:f.getLang(),newLang:null,reset:function(){this.currentLang=f.getLang();this.newLang=null},id:"lang"},k=[{id:"options",label:d.lang.scayt.optionsTab,elements:[{type:"vbox",id:"scaytOptions",
children:function(){var b=f.getApplicationConfig(),c=[],a={"ignore-all-caps-words":"allCaps","ignore-domain-names":"ignoreDomainNames","ignore-words-with-mixed-cases":"mixedCase","ignore-words-with-numbers":"mixedWithDigits"},e;for(e in b){var g={type:"checkbox"};g.id=e;g.label=d.lang.scayt[a[e]];c.push(g)}return c}(),onShow:function(){this.getChild();for(var b=d.scayt,c=0;c<this.getChild().length;c++)this.getChild()[c].setValue(b.getApplicationConfig()[this.getChild()[c].id])}}]},{id:"langs",label:d.lang.scayt.langs,
elements:[{id:"leftLangColumn",type:"vbox",align:"left",widths:["100"],children:[{type:"html",id:"langBox",style:"overflow: hidden; white-space: normal;",html:'<form><div style="float:left;width:45%;margin-left:5px;" id="left-col-'+d.name+'"></div><div style="float:left;width:45%;margin-left:15px;" id="right-col-'+d.name+'"></div></form>',onShow:function(){var b=f.getLang();l.getById("scaytLang_"+b).$.checked=!0}}]}]},{id:"dictionaries",label:d.lang.scayt.dictionariesTab,elements:[{type:"vbox",id:"rightCol_col__left",
children:[{type:"html",id:"dictionaryNote",html:""},{type:"text",id:"dictionaryName",label:f.getLocal("dname")||"Dictionary name",onShow:function(b){var c=b.sender,a=d.scayt;setTimeout(function(){c.getContentElement("dictionaries","dictionaryNote").getElement().setText("");null!=a.getUserDictionaryName()&&""!=a.getUserDictionaryName()&&c.getContentElement("dictionaries","dictionaryName").setValue(a.getUserDictionaryName())},0)}},{type:"hbox",id:"notExistDic",align:"left",style:"width:auto;",widths:["50%",
"50%"],children:[{type:"button",id:"createDic",label:d.lang.scayt.dic_create,title:d.lang.scayt.dic_create,onClick:function(){var b=this.getDialog(),c=j,a=d.scayt,e=b.getContentElement("dictionaries","dictionaryName").getValue();a.createUserDictionary(e,function(a){a.error||c.toggleDictionaryButtons.call(b,!0);a.dialog=b;a.command="create";a.name=e;d.fire("scaytUserDictionaryAction",a)},function(a){a.dialog=b;a.command="create";a.name=e;d.fire("scaytUserDictionaryActionError",a)})}},{type:"button",
id:"restoreDic",label:d.lang.scayt.dic_restore,title:d.lang.scayt.dic_restore,onClick:function(){var b=this.getDialog(),c=d.scayt,a=j,e=b.getContentElement("dictionaries","dictionaryName").getValue();c.restoreUserDictionary(e,function(c){c.dialog=b;c.error||a.toggleDictionaryButtons.call(b,!0);c.command="restore";c.name=e;d.fire("scaytUserDictionaryAction",c)},function(a){a.dialog=b;a.command="restore";a.name=e;d.fire("scaytUserDictionaryActionError",a)})}}]},{type:"hbox",id:"existDic",align:"left",
style:"width:auto;",widths:["50%","50%"],children:[{type:"button",id:"removeDic",label:d.lang.scayt.dic_delete,title:d.lang.scayt.dic_delete,onClick:function(){var b=this.getDialog(),c=d.scayt,a=j,e=b.getContentElement("dictionaries","dictionaryName"),g=e.getValue();c.removeUserDictionary(g,function(c){e.setValue("");c.error||a.toggleDictionaryButtons.call(b,!1);c.dialog=b;c.command="remove";c.name=g;d.fire("scaytUserDictionaryAction",c)},function(a){a.dialog=b;a.command="remove";a.name=g;d.fire("scaytUserDictionaryActionError",
a)})}},{type:"button",id:"renameDic",label:d.lang.scayt.dic_rename,title:d.lang.scayt.dic_rename,onClick:function(){var b=this.getDialog(),c=d.scayt,a=b.getContentElement("dictionaries","dictionaryName").getValue();c.renameUserDictionary(a,function(c){c.dialog=b;c.command="rename";c.name=a;d.fire("scaytUserDictionaryAction",c)},function(c){c.dialog=b;c.command="rename";c.name=a;d.fire("scaytUserDictionaryActionError",c)})}}]},{type:"html",id:"dicInfo",html:'<div id="dic_info_editor1" style="margin:5px auto; width:95%;white-space:normal;">'+
d.lang.scayt.dic_info+"</div>"}]}]},{id:"about",label:d.lang.scayt.aboutTab,elements:[{type:"html",id:"about",style:"margin: 5px 5px;",html:'<div><div id="scayt_about_">'+k+"</div></div>"}]}];d.on("scaytUserDictionaryAction",function(b){var c=b.data.dialog,a=c.getContentElement("dictionaries","dictionaryNote").getElement(),e;void 0===b.data.error?(e=f.getLocal("dic_"+b.data.command+"_suc"),e=e.replace("%s",b.data.name),a.setText(e),SCAYT.$(a.$).css({color:"blue"})):(""===b.data.name?a.setText(f.getLocal("dic_empty_name")):
(e=f.getLocal("dic_"+b.data.command+"_err"),e=e.replace("%s",b.data.name),a.setText(e)),SCAYT.$(a.$).css({color:"red"}),null!=f.getUserDictionaryName()&&""!=f.getUserDictionaryName()?c.getContentElement("dictionaries","dictionaryName").setValue(f.getUserDictionaryName()):c.getContentElement("dictionaries","dictionaryName").setValue(""))});d.on("scaytUserDictionaryActionError",function(b){var c=b.data.dialog,a=c.getContentElement("dictionaries","dictionaryNote").getElement(),e;""===b.data.name?a.setText(f.getLocal("dic_empty_name")):
(e=f.getLocal("dic_"+b.data.command+"_err"),e=e.replace("%s",b.data.name),a.setText(e));SCAYT.$(a.$).css({color:"red"});null!=f.getUserDictionaryName()&&""!=f.getUserDictionaryName()?c.getContentElement("dictionaries","dictionaryName").setValue(f.getUserDictionaryName()):c.getContentElement("dictionaries","dictionaryName").setValue("")});var j={title:d.lang.scayt.title,resizable:CKEDITOR.DIALOG_RESIZE_BOTH,minWidth:340,minHeight:260,onLoad:function(){if(0!=d.config.scayt_uiTabs[1]){var b=j,c=b.getLangBoxes.call(this);
c.getParent().setStyle("white-space","normal");b.renderLangList(c);this.definition.minWidth=this.getSize().width;this.resize(this.definition.minWidth,this.definition.minHeight)}},onCancel:function(){i.reset()},onHide:function(){d.unlockSelection()},onShow:function(){d.fire("scaytDialogShown",this);if(0!=d.config.scayt_uiTabs[2]){var b=d.scayt,c=this.getContentElement("dictionaries","dictionaryName"),a=this.getContentElement("dictionaries","existDic").getElement().getParent(),e=this.getContentElement("dictionaries",
"notExistDic").getElement().getParent();a.hide();e.hide();null!=b.getUserDictionaryName()&&""!=b.getUserDictionaryName()?(this.getContentElement("dictionaries","dictionaryName").setValue(b.getUserDictionaryName()),a.show()):(c.setValue(""),e.show())}},onOk:function(){var b=j;this.getContentElement("options","scaytOptions");b=b.getChangedOption.call(this);f.commitOption({changedOptions:b})},toggleDictionaryButtons:function(b){var c=this.getContentElement("dictionaries","existDic").getElement().getParent(),
a=this.getContentElement("dictionaries","notExistDic").getElement().getParent();b?(c.show(),a.hide()):(c.hide(),a.show())},getChangedOption:function(){var b={};if(1==d.config.scayt_uiTabs[0])for(var c=this.getContentElement("options","scaytOptions").getChild(),a=0;a<c.length;a++)c[a].isChanged()&&(b[c[a].id]=c[a].getValue());i.isChanged()&&(b[i.id]=d.config.scayt_sLang=i.currentLang=i.newLang);return b},buildRadioInputs:function(b,c){var a=new CKEDITOR.dom.element("div");CKEDITOR.document.createElement("div");
var e="scaytLang_"+c,g=CKEDITOR.dom.element.createFromHtml('<input id="'+e+'" type="radio"  value="'+c+'" name="scayt_lang" />'),f=new CKEDITOR.dom.element("label"),h=d.scayt;a.setStyles({"white-space":"normal",position:"relative"});g.on("click",function(a){i.newLang=a.sender.getValue()});f.appendText(b);f.setAttribute("for",e);a.append(g);a.append(f);c===h.getLang()&&(g.setAttribute("checked",!0),g.setAttribute("defaultChecked","defaultChecked"));return a},renderLangList:function(b){var c=b.find("#left-col-"+
d.name).getItem(0),b=b.find("#right-col-"+d.name).getItem(0),a=f.getLangList(),e={},g=[],i=0,h;for(h in a.ltr)e[h]=a.ltr[h];for(h in a.rtl)e[h]=a.rtl[h];for(h in e)g.push([h,e[h]]);g.sort(function(a,c){var b=0;a[1]>c[1]?b=1:a[1]<c[1]&&(b=-1);return b});e={};for(a=0;a<g.length;a++)e[g[a][0]]=g[a][1];g=Math.round(g.length/2);for(h in e)i++,this.buildRadioInputs(e[h],h).appendTo(i<=g?c:b)},getLangBoxes:function(){return this.getContentElement("langs","langBox").getElement()},contents:function(b,c){var a=
[],e=c.config.scayt_uiTabs;if(e){for(var d in e)1==e[d]&&a.push(b[d]);a.push(b[b.length-1])}else return b;return a}(k,d)};return j});